### ISSUE TITLE
is it possible that when you click on one movie/serie, start it  immediately without popup?

### ISSUE THREAD

**Issue by DanielTizon** [tuxfuxch/yarc#6] opened 2015-12-02 17:50 UTC
Hi, Im having some problems with movies/series popup. For example, when I click in one movie, it get activated (white background) but nothing happens, and when I use the "back" key in the phone, then I get the popup. I dont know why it is happening. Im using Asus Zenfone 2 (5.5 inch), android 5.0, and firefox for android.

I have been trying modify index.html but I'm not able to do that a movie/serie start immediately when I click on it without show a popup. Is it possible? any tip about how to achieve it?

Thanks!!

**Comment by tuxfuxch** [comment] 2015-12-02 21:02
hey Daniel,
well, that changed already, but is not on github yet ;)
i had some (only slight) problems with popups too. i test with firefox for android, but i had not the problems you face...
nonetheless i changed it as i said. if you use the latest from github (0.9.10) then you can see how it will be in the next version in the addon section. there it's not a popup, it seems like an own site (but it's actually not). what i do is to hide the "details" and show the library, and if you open something, it fills the details, shows it and hides the library (or the other way around). 
because of your description, i realised, that the way i do it with my local dev copy, the back-button goes to another page (like remote, or addons or whatever). do you think it would be much better  to be able to use the back button to get from the details to the library (you can test it in the latest version in addons)?
your opinion would be appreciated.

edit: oh and no, it's not possible to start imediatelly
if it's very important to you, i can give you the actual dev state, but you would face more bugs and problems.

**Comment by DanielTizon** [comment] 2015-12-03 11:30
Unfortunately It doesnt show up any addon (even when I have installed yarc like web interface addon).

 Anyways what you are saying sounds great. If I have understood well, when you select a movie/tv show, you would get a full screen page with details of the selected item and play button, trailer, etc., and then if you press back button you go back to the library. 

Atm I have done a workaround, use chrome instead of firefox, and I have disabled "div's" about plot, genres, and other info of movie/tv show, then the popup show up in a correct size in my phone screen,

**Comment by tuxfuxch** [comment] 2015-12-03 12:00
Hi Daniel
oh ok so you don't use a lot of them :) what i didn't mention anywhere, is that i don't show all addons. scrapers and webinterfaces are useless on this interface. i only load the addons with type "xbmc.python.pluginsource". sorry about this confusion.

if you like jazz you could install "JazzRadio.com" from the kodi repo in music-addons to try. this sould show up.

the second part: well nearly. it apears as a full page, but it's not, it's still the same page with the library hidden. so the back button won't work. i did not realise that, so thanks you i know that now and i think about changing it.

sorry that you have to do the workaround. please be a bit patient. it will be better with the next version i hope.

btw: since you don't use addons (where my plugin is a bit better than others i think), chorus is worth a try. it's quite great. mine is better in addons and navigating, but most other stuff with libraries, the webinterface chorus (kodi main repo) does a very good job also on mobiles. might be worth a try for you.

**Comment by DanielTizon** [comment] 2015-12-03 12:42
I already tried Chorus, and I didn't like it, it wasnt working like I want.

So Im staying with Yarc ^^

I'll look forward a new update! :)

**Comment by tuxfuxch** [comment] 2015-12-04 12:52
ok i had a look into it. i will do as i said, but unfortunately, it will still not be very consistent. it will be ok for the movie, series and music page. but in addons, it's quite difficult to add the backpath within the addon navigation. this will need some major changes. 
For your use case (as i understand it) it will be quite good. for "havy" addon users, the perfection has to wait for another release.
that's why i will keep the issue open.

**Comment by tuxfuxch** [comment] 2015-12-11 12:33
Update: i thought i have a simple solution. my implementation did work, but had some major downsides. so i have to go back and find another way. i have already a promising idea, but it will take some more time. but i am positive i can do it for the next release which will be early next year.

**Comment by tuxfuxch** [comment] 2015-12-16 11:18
Update2: ok finally i did it! it was not easy to find a way (i had to ditch my first idea, but the way it works is quite similar in principle) but it works now. to clarify: the title of the issue is now wrong. it's not possible to start items immediately. it still opens the details. but it's not a popup any more, and you can use the back button, or the close button to go back to the overview.

this new function will be introduced in version 0.9.12 released to be released in january. version 0.9.11 was not released.

thanks for the issue, i think it makes yarc a lot better, wouldn't have come to this improvement without you. are you satisfyed with this (presumed it works good on your device as described here)?
if no, please tell me what you expected. if yes, i would like to close the issue.

thanks!

PS: what i did not do so far, but i plan to, is using the back button also in reduced lists to go back and forth within the list. this will be a major pain in the a.. because it's really difficult to implement. i don't see trough that yet, and may need some major rework of the code as it is.

**Comment by tuxfuxch** [comment] 2015-12-17 13:46
Hi 
ok i did it, just to realize, it's a bad idea. i had to build back. punchline:
- the details are not popup anymore
- you can go back from details to overview with the browsers back button

downside: if you are in movie details, change to remote and go to movie, it will not show the details, but the overview. to get to the details directly you have also to use the back button.
this is a compromise which is the best of the worse options. but i you can life with it.
the next version will not be 0.9.12 but 0.10.0 and will most probably released this year.

**Closed as completed** 2015-12-17 13:46 UTC

**Comment by DanielTizon** [comment] 2015-12-17 14:35
Hi tuxfuxch,

I'm looking forward to testing the new version. If you need that I test the application before release, just send me the code and I'll try it.

**Comment by tuxfuxch** [comment] 2015-12-17 14:43
ok, thanks. i think it's ok like this. no need to test. but when released, and you are not satisfied, you can write here and i reopen this issue, or you can make a new one. as long it's not 1.0.0, changes (and back-changes) must be expected.

**Comment by tuxfuxch** [comment] 2015-12-18 17:02
ok new version is ready to download. try it out! hope it's fine like this.

**Comment by DanielTizon** [comment] 2015-12-21 08:52
Hey mate,

I already tried it, and it works great, I think that you made a nice work.

Thanks!
